# dataset preprocess
dataset:
  resample: ~
  high_freq: ~
  low_freq: ~
  n_classes: 4
  channels: ~
  start_offset: -0.5
  stop_offset: 0
# fit hyperparameters
fit:
  seed: 42
  verbose: 0
  epochs: 500
  lr: 0.001
  batch_size: 64