# dataset preprocess
dataset:
  resample: ~
  high_freq: ~
  low_freq: ~
  n_classes: 4
  channels: ~
  start_offset: -1
  stop_offset: 1
# fit hyperparameters
fit:
  verbose: 1
  seed: 42
  epochs: 15
  lr: 0.001
  batch_size: 64
# specific model options
model:
  kernel_length_t: 8
  bias_s: no
