dataset:
  resample: ~
  high_freq: ~
  low_freq: ~
  n_classes: 4
  channels: ['Fpz', 'AF7', 'AF8', 'AFz', 'F1', 'F2', 'F5', 'F6', 'FT7', 'FCz', 'FC4', 'FT8', 'T9', 'C5','C1', 'C2',
             'C6', 'T10', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'P1', 'P2', 'P5', 'P6', 'PO7', 'POz', 'PO8', 'Oz']
fit:
  seed: 20011025
  epochs: 200
  lr: 0.001
  batch_size: 64
model:
  graph_strategy: AG