
dataset:
  resample: ~
  high_freq: ~
  low_freq: ~
  n_classes: 4
  channels: ['C6', 'Fpz', 'Pz', 'T10', 'AFz', 'CP5', 'FC1', 'C1', 'F2', 'Oz', 'T9', 'CPz','Fp2', 'P4', 'Fp1', 'Cz']
fit:
  seed: 20011025
  epochs: 200
  lr: 0.001
  batch_size: 64
model:
  graph_strategy: AG
  kernel_length_t: 8
  bias_s: no