dataset:
  resample: ~
  high_freq: ~
  low_freq: ~
  n_classes: 4
  channels: ['AF7', 'P3', 'P1', 'FC3', 'FT7', 'PO3', 'FT8', 'F8', 'O2', 'PO7', 'PO8', 'TP8', 'F6', 'PO4','CP4', 'AF3']
fit:
  seed: 20011025
  epochs: 200
  lr: 0.001
  batch_size: 64
model:
  graph_strategy: AG
  kernel_length_t: 8
  bias_s: no

# 63.11