dataset:
  resample: ~
  high_freq: ~
  low_freq: ~
  n_classes: 3
  channels: ['FC3', 'AF7', 'P1', 'FT7', 'P3', 'PO7', 'PO3', 'O2', 'PO4', 'PO8', 'FT8', 'F8', 'TP8', 'Pz', 'C6', 'F6']
fit:
  seed: 3498
  epochs: 200
  lr: 0.001
  batch_size: 64
model:
  graph_strategy: AG
  kernel_length_t: 8
  bias_s: yes

# 71.39